---
version: "3.6"
networks:
  bridge:
services:
  ruby_build:
    image: titokyo/riak_docs_generator
    build:
      context: .
      no_cache: true
    container_name: riak_ruby_build
    environment:
      - TZ=Asia/Tokyo
      - RAKE_GEN_DOWNS=false
      - RAKE_GEN_PROJECTS=true
    volumes:
      - type: bind
        source: ..
        target: /src
        read_only: false
      - type: bind
        source: ../output
        target: /src/output
        read_only: false
    networks:
      - bridge
  riakdocs:
    build:
      context: .
      dockerfile: hugo.Dockerfile
    depends_on:
      ruby_build:
        condition: service_completed_successfully
    container_name: riakdocs
    environment:
      - TZ=Asia/Tokyo
      - HUGO_WATCH=true
      - HUGO_BASEURL=http://localhost/riak-docs/
      - HUGO_PORT=1314
    ports:
      - 1314:1314 # $HUGO_PORT
    volumes:
      - type: bind
        source: ..
        target: /src
        read_only: false
      - type: bind
        source: ../output
        target: /src/output
        read_only: false
    networks:
      - bridge    
